#!/bin/sh /etc/rc.common

START=50
STOP=50

USE_PROCD=1

start_service() {
    procd_open_instance
    # Disable password
    procd_set_param command /usr/sbin/telnetd -F -l /bin/ash
    # Enable password
    #procd_set_param command /usr/sbin/telnetd -F -l /bin/login
    procd_set_param respawn
    procd_close_instance
}

stop_service() {
    killall telnetd 2>/dev/null
}

